CREATE DATABASE plantsiodb;
USE plantsiodb;

CREATE TABLE plantsIOTable (id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,plant_moisture DECIMAL(30) NOT NULL,plant_temp DECIMAL(30) NOT NULL, plant_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP);


